name: m_mart_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  logger: ^2.3.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0
  flutter_easyloading: ^3.0.5
  dot_navigation_bar: ^1.0.2
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  url_launcher: ^6.2.4
  flutter_staggered_animations: ^1.1.1
  upgrader: ^9.0.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  syncfusion_flutter_pdfviewer: ^24.1.47
  shimmer: ^3.0.0
  dynamic_height_grid_view: ^0.0.4
  permission_handler: ^11.2.0
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.2.2
  lottie: ^3.0.0
  dio: ^5.4.1
  awesome_dialog: ^3.1.0
  flutter_form_builder: ^9.2.1
  rotated_corner_decoration: ^2.1.0+1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.3.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  flutter_local_notifications: ^17.2.1+2
  flutter_animate: ^4.5.0
  soft_builder:
    git: https://github.com/rezasoftbd/soft_builder.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  connectivity_plus: ^6.0.3
  dropdown_button2: ^2.3.9
  see_more: ^0.0.5


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/png/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
